### ISSUE TITLE
Add me as a collaborator.

### ISSUE THREAD

**Issue by Batcave765** [ironman9356/SoulBlade#1]
This is me, Batcave765. I can't find the "Collaborator Request" label.

**Comment by arghanath007** [comment]
![image](https://github.com/ironman9356/SoulBlade/assets/54589605/92a2be4e-5205-4a4b-8001-84994deac1ae)

Click on `label` and you are good to go.

**Comment by ironman9356** [comment]
Bat you are already added.

Adding Mr Wick
